
### GET ALL
GET https://ocapi-production-5d91.up.railway.app/api/colors

### GET ONE
GET https://ocapi-production-5d91.up.railway.app/api/colors/4

### ADD
POST https://ocapi-production-5d91.up.railway.app/api/colors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODQyOTg5MiwiZXhwIjoxNzA4NDQwNjkyfQ.V5WAPDTiAw5BNfP0L3W93IL2kIKaSej1XdOyk7LqIRQ

{
    "name": "Negro",
    "background": "#FF0000"
}

### UPDATE
PUT https://ocapi-production-5d91.up.railway.app/api/colors/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODQyOTg5MiwiZXhwIjoxNzA4NDQwNjkyfQ.V5WAPDTiAw5BNfP0L3W93IL2kIKaSej1XdOyk7LqIRQ

{
    "background": "#0000"
}


### UPDATE
PATCH  https://ocapi-production-5d91.up.railway.app/api/colors/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODEyNzQwNiwiZXhwIjoxNzA4MTM4MjA2fQ.VpZViPutljF0o50ffyoPrhIt_NcRrY0maFkUfIbwusQ

{
    "background": "#FF0000",
}

###REMOVE
DELETE https://ocapi-production-5d91.up.railway.app/api/colors/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODEwMjU2NCwiZXhwIjoxNzA4MTEzMzY0fQ.G18emOWNOUsoQDX5UYd6hC2xxapCmxkq3KJZqElbVtg
