
### LOGIN
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "luciacappll@gmail.com",
    "password": "test123"
}



### SIGNUP
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "email": "luciacappll@gmail.com",
    "password": "test123",
    "firstName": "Lucía",
    "lastName": "Cappellini",
    "role": "admin"
}


### SIGNUP
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "email": "juankp@gmail.com",
    "password": "test1234",
    "firstName": "Juan",
    "lastName": "Cappellini",
    "role": "user"
}
