
### GET ALL
GET http://localhost:3000/api/promotions

### GET ONGOING
GET https://ocapi-production-5d91.up.railway.app/api/promotions/ongoing

### GET ONGOING FOR PRODUCT
GET https://ocapi-production-5d91.up.railway.app/api/promotions/ongoing/1

### FIND ONE
GET https://ocapi-production-5d91.up.railway.app/api/promotions/4

### CREATE
POST https://ocapi-production-5d91.up.railway.app/api/promotions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODEzODY2OCwiZXhwIjoxNzA4MTQ5NDY4fQ.kjE30_Qlu9i16lIPhYgjCbJuHs289-xqtwzL9eHVsBA

{
     "title": "Hockey Back!",
      "description": null,
      "validFrom": "2024-03-01",
      "validUntil": "2024-05-31",
      "discountPercent": "0.15"
}

### UPDATE
PUT https://ocapi-production-5d91.up.railway.app/api/promotions/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODEzODY2OCwiZXhwIjoxNzA4MTQ5NDY4fQ.kjE30_Qlu9i16lIPhYgjCbJuHs289-xqtwzL9eHVsBA


{
      "title": "School Back!",
      "description": null,
      "validFrom": "2024-02-01",
      "validUntil": "2024-03-31",
      "discountPercent": "0.15"
}


### UPDATE
PATCH https://ocapi-production-5d91.up.railway.app/api/promotions/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODEzODY2OCwiZXhwIjoxNzA4MTQ5NDY4fQ.kjE30_Qlu9i16lIPhYgjCbJuHs289-xqtwzL9eHVsBA

{
    "validUntil": "2024-03-27",
}



### DELETE
DELETE  https://ocapi-production-5d91.up.railway.app/api/promotions/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODEzODY2OCwiZXhwIjoxNzA4MTQ5NDY4fQ.kjE30_Qlu9i16lIPhYgjCbJuHs289-xqtwzL9eHVsBA
