
### GET ALL
GET https://ocapi-production-5d91.up.railway.app/api/brands

### GET ONE
GET https://ocapi-production-5d91.up.railway.app/api/brands/1

### ADD
POST https://ocapi-production-5d91.up.railway.app/api/brands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODQyOTg5MiwiZXhwIjoxNzA4NDQwNjkyfQ.V5WAPDTiAw5BNfP0L3W93IL2kIKaSej1XdOyk7LqIRQ

{
    "name": "Ray"
}

### UPDATE
PUT https://ocapi-production-5d91.up.railway.app/api/brands/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODM1NTAyNSwiZXhwIjoxNzA4MzY1ODI1fQ.qZzGf5W-FU8jOC4UfZZh4CLz3eQwqss7fJzHWAGE9eE


{
    "name": "Rusty"
}

### UPDATE
PATCH https://ocapi-production-5d91.up.railway.app/api/brands/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODEyNzQwNiwiZXhwIjoxNzA4MTM4MjA2fQ.VpZViPutljF0o50ffyoPrhIt_NcRrY0maFkUfIbwusQ

{
    "name": "Ray Ban"
}

### REMOVE
DELETE http://localhost:3000/api/brands/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwOTI5MjEzNCwiZXhwIjoxNzA5MzAyOTM0fQ.BHtqlrGh89_NUl3edKvLafZzyQr8jssONr-zITqvhcQ