
### GET ALL
GET http://localhost:3000/api/products

### GET ONE
GET http://localhost:3000/api/products/4

### CREATE
POST http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODM2OTUwMSwiZXhwIjoxNzA4MzgwMzAxfQ.PXnmDDQdHEGPJr-JkSN8OnAn0wjudcjK4mQmIXM_NAA

{
    "name": "Ground",
    "price": 90000,
    "category": 2,
    "brand": 2,
    "colors": [5]
}

### UPDATE
PUT http://localhost:3000/api/products/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODM2OTUwMSwiZXhwIjoxNzA4MzgwMzAxfQ.PXnmDDQdHEGPJr-JkSN8OnAn0wjudcjK4mQmIXM_NAA

{
    "name": "Dapper",
    "price": 90000,
    "category": 2,
    "brand": 2,
    "colors": [4]
}

### UPDATE
PATCH http://localhost:3000/api/products/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODM2OTUwMSwiZXhwIjoxNzA4MzgwMzAxfQ.PXnmDDQdHEGPJr-JkSN8OnAn0wjudcjK4mQmIXM_NAA

{
    "colors": [4,5]
}


### REMOVE
DELETE http://localhost:3000/api/products/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1Y2lhY2FwcGxsQGdtYWlsLmNvbSIsImZpcnN0TmFtZSI6Ikx1Y8OtYSIsImxhc3ROYW1lIjoiQ2FwcGVsbGluaSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwODEwMjU2NCwiZXhwIjoxNzA4MTEzMzY0fQ.G18emOWNOUsoQDX5UYd6hC2xxapCmxkq3KJZqElbVtg
